---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: pretty-format-json
            args:
                - --autofix
    - repo: https://github.com/ComPWA/taplo-pre-commit
      rev: v0.9.3
      hooks:
          - id: taplo-format
            files: ^internal/.*\.toml$
          - id: taplo-lint
            files: ^internal/.*\.toml$
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt
    - repo: https://github.com/tekwizely/pre-commit-golang
      rev: v1.0.0-rc.2
      hooks:
          - id: go-fmt
          - id: golangci-lint-repo-mod
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck
            entry: shellcheck --shell=bash
    - repo: https://github.com/crate-ci/typos
      rev: v1.35.6
      hooks:
          - id: typos
    - repo: local
      hooks:
          - id: commintlint
            name: lint commit message
            stages: [commit-msg]
            entry: npx commitlint --edit
            language: system
